ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'GERENTE_COMERCIAL';
ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'VENDEDOR';
ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'ADMINISTRATIVO';

ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS "vendedor_id" UUID;

ALTER TABLE "user"
ADD CONSTRAINT "user_vendedor_id_fkey"
FOREIGN KEY ("vendedor_id") REFERENCES "vendedor"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
