-- Tipo de cambio USD→MXN del deal, espejo del que ya tiene orden_venta.
--
-- Sin esta columna, el valor del pipeline sumaba un deal en dólares como si fueran pesos y
-- rotulaba el total "MXN": con TC ~17, un deal de USD 50.000 entraba como $50.000 y
-- subvaluaba el pipeline en casi un millón por cada uno.
--
-- ADITIVA: solo agrega una columna nullable. No toca datos existentes ni borra nada, así que
-- el guard de migraciones destructivas la deja pasar. Los deals que ya están en USD quedan
-- SIN tipo de cambio, y eso es correcto: la app los declara como "no convertibles" en vez de
-- inventarles una paridad (lib/net-amounts). Ponerles un valor acá sería inventar el dato.
-- IF NOT EXISTS porque producción YA tiene esta columna, con la definición exacta que esta
-- línea crearía: numeric(10,4), nullable, sin default (verificado contra information_schema).
-- Entró fuera del flujo de migraciones —el drift que CLAUDE.md tiene anotado— y sin esto el
-- `prisma migrate deploy` del build falla con "column already exists" y ABORTA el deploy
-- entero, porque en vercel.json corre antes de `next build`.
--
-- La alternativa era `prisma migrate resolve --applied` contra prod, pero eso obliga a sacar
-- la cadena de conexión de producción a una máquina, que es justo lo que las reglas del repo
-- evitan. Así es idempotente: en prod no hace nada, en una base limpia crea la columna igual.
ALTER TABLE "deal" ADD COLUMN IF NOT EXISTS "tipo_cambio" DECIMAL(10,4);
